# Generated by Django 4.1.6 on 2023-04-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='webapp.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='webapp.type', verbose_name='Type'),
        ),
    ]
